### ISSUE TITLE
Header: Menu Dropdown hidden behind marquee

### ISSUE THREAD

**Issue by mdctenga** [grommet/hpe-digitaltoolkit#86] opened 2016-06-20 21:06 UTC

**Comment by mdctenga** [comment] 2016-06-20 21:10
Environment:
- iOS 9.3.2
- iPod touch 6 [specs](http://www.apple.com/ipod-touch/specs/)

What should happen:
- User should be able to read the "Menu" drop-down.

What's currently happening:
- ![Menu](https://cloud.githubusercontent.com/assets/8364525/16210304/18d9485c-36d7-11e6-8ed1-578a71665ed3.png)

**Comment by phuson** [comment] 2016-06-20 22:02
FYI, this issue is not related to the Marquee component. Seems like an issue related to Grommet core. I'll update once I have more detail what the issue is.

**Comment by phuson** [comment] 2016-06-20 22:52
Created a PR for fixing this in Grommet core: https://github.com/grommet/grommet/pull/647

**Comment by phuson** [comment] 2016-06-21 19:55
@mdctenga please review this. It should be fixed now on http://hpe-toolkit.herokuapp.com/docs/hpe/examples

**Closed** 2016-06-21 20:46 UTC
Labels: ready for QA
